/* Progressive photo loading for the fotografie selectie grid.
   Images start as low-res thumbnails (generated by scripts/generate_foto_thumbs.py)
   and swap to the high-res original (data-full) once they scroll near the viewport.
   The thumb stays visible as a placeholder (background) while the high-res fades in. */
(function () {
    'use strict';

    function loadHighRes(img, onDone) {
        if (img.dataset.loaded || !img.dataset.full) return;
        img.dataset.loaded = '1';

        var probe = new Image();
        probe.decoding = 'async';
        probe.onload = function () {
            img.src = img.dataset.full;
            img.onload = function () { img.style.opacity = '1'; };
            if (img.complete && img.naturalWidth > 0) img.style.opacity = '1';
            if (onDone) onDone(true);
        };
        probe.onerror = function () {
            img.dataset.loaded = ''; // allow a later retry
            if (onDone) onDone(false);
        };
        probe.src = img.dataset.full;
    }

    function init() {
        var imgs = Array.prototype.slice.call(document.querySelectorAll('#assignment_desc img[data-full]'));
        if (!imgs.length) return;

        var sections = Array.prototype.slice.call(document.querySelectorAll('.section_title[data-section]'));
        sections.forEach(function (section) {
            var id = section.getAttribute('data-section');
            if (id && !section.id) {
                section.id = id;
            }
        });

        var navLinks = Array.prototype.slice.call(document.querySelectorAll('#nav_list .nav_link[data-section]'));
        function updateActiveSection() {
            if (!sections.length || !navLinks.length) {
                return;
            }
            var scrollY = window.pageYOffset || window.scrollY || 0;
            var current = sections[0].getAttribute('data-section') || '';
            sections.forEach(function (section) {
                var top = section.getBoundingClientRect().top + scrollY;
                if (scrollY >= top - 160) {
                    current = section.getAttribute('data-section') || current;
                }
            });
            navLinks.forEach(function (link) {
                link.classList.toggle('active', link.getAttribute('data-section') === current);
            });
        }
        window.addEventListener('scroll', updateActiveSection, { passive: true });
        updateActiveSection();

        imgs.forEach(function (img) {
            var fig = img.closest('figure.image-full') || img.parentNode;
            if (fig) {
                fig.style.backgroundImage = 'url("' + img.src + '")';
                fig.style.backgroundSize = 'cover';
                fig.style.backgroundPosition = 'center';
            }
            img.style.opacity = '0';
            img.style.transition = 'opacity 0.4s ease';
        });

        if (typeof IntersectionObserver === 'undefined') {
            imgs.forEach(loadHighRes);
            return;
        }

        var observer = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (!entry.isIntersecting) return;
                // Only stop observing once the high-res image actually loads -
                // on failure dataset.loaded is cleared for a retry, but that
                // retry can only happen while still observed.
                loadHighRes(entry.target, function (success) {
                    if (success) observer.unobserve(entry.target);
                });
            });
        }, { rootMargin: '600px 0px' });

        imgs.forEach(function (img) {
            if (img.dataset.loaded) return;
            observer.observe(img);
        });
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
